---
abstract: 'URI objects optimised for manipulation'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-Builder
provides:
  URI::Builder:
    file: lib/URI/Builder.pm
    version: 0.02
requires:
  URI: 1.60
version: 0.02
